/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */
//Address define
#define RCC_BASE    0x40021000
#define PORTA_BASE  0x40010800
//Registers define
#define RCC_APB2ENR    *((volatile int *)(RCC_BASE+0x18))
#define PORTA_CRH      *((volatile int *)(PORTA_BASE+0x04))
#define PORTA_ODR      *((volatile int *)(PORTA_BASE+0x0C))

int main(void)
{
	RCC_APB2ENR |= (1<<2);
	PORTA_CRH &= 0xff0fffff;
	PORTA_CRH |= 0x00200000;

	while(1)
	{
		PORTA_ODR |= (1<<13);
		for(int i=0;i<100000;i++);
		PORTA_ODR &= ~(1<<13);
		for(int i=0;i<100000;i++);
	}
	return 0;
}
